### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by 01Kuzma** [catch-IT/grav-image-server#2]
Hi!
Can't run it on XAMPP (Windows) nor Shared Hosting.
PHP 7.4
It throws this error:
`Parse error: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in /xxx/public_html/user/plugins/image-server/image-server.php on line 80`

**Comment by xf-** [comment]
Missed that issue notification.

There is no PHP 7.4 support. It is already end-of-life and at start of development, this and all; common plugins in grav had PHP8 support.
PHP8 needs no unused variable in an exception.

https://docs.catchit.xyz/grav-plugins/image-server/base/#installation

**Comment by 01Kuzma** [comment]
Thank you for the answer!
I haven't noticed the minimum requirements at the beginning.
I've upgraded my localhost to PHP 8.0 and it works.
Thank you!
